### ISSUE TITLE
File not found error when pointing to a non-existant directory looks slightly wrong

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/DBuildTest#2]
DyalogBuild version 1.24

* Command Execution Failed: File not found: u:/tmp/andys/dyalog-tube.dyalogbuild
      ]dbuild u:/tmp/andys/xxx
* Command Execution Failed: File not found: u:/tmp/andys/xxx.dyalogbuild

Shouldn't that be u:/tmp/andys/xxx/xxx.dyalogbuild ?

**Comment by mbaas2** [comment]
Sorry, can't repro:
```
      ]dbuild u:/tmp/andys/xxx/xxx.dyalogbuild
* Command Execution Failed: File not found: u:/tmp/andys/xxx/xxx.dyalogbuild

```
