### ISSUE TITLE
Shorten CodeCoverage_Subject

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/DBuildTest#9]
BB suggested: CoCo_Scope

**Comment by mbaas2** [comment]
or maybe even CoCoScope...

**Comment by mbaas2** [comment]
Rodrigo pointed out that `cocó` in portugese means💩 and `coco` stands for 🥥. But he did not feel "linguistically offended and encouraged usage of coco (but also suggested the alternative `-cc`).

**Comment by mkromberg** [comment]
Or just "Coverage"

**Comment by mbaas2** [comment]
Yep, I guess that would also work. And the switch could also be `-Coverage` - we have one other switch that uses `-c`, so `-co` would be the shortest possible form that could be used.

Should I go ahead with that?

**Comment by mkromberg** [comment]
I like that, and I have little interest in trying to have the shortest possible switch names.
